### ISSUE TITLE
Tracking issue: Move all used routes to backend

### ISSUE THREAD

**Issue by Urhengulas** [FaceTheFacts/backend#18]
- [x] `GET /candidates/<politician_id>`: get politician data
- [ ] `GET /candidates/?...`: search politicians
- [x] `GET /candidacies-mandates?politician_id=<politician_id>`
- [ ] `committee-memberships?candidacy_mandate[entity.label][cn]=${candidate.label} (Bundestag 2017 - 2021)`
- [ ] `sidejobs?mandates[entity.label][cn]=${candidate.label}&range_end=100`
- [ ] `votes?poll=${props.vote.id}&mandate[entity.label][cn]=${props.name}`
- [ ] `polls/${pollId}`
